import OpenAI from "openai";
import { zodResponseFormat } from "openai/helpers/zod";
import { buildDateRange, getDateSpanDays } from "@/lib/date-utils";
import { buildTravelUserPrompt, TRAVEL_SYSTEM_PROMPT } from "@/lib/prompts";
import { withRetry, withTimeout } from "@/lib/retry";
import type { TravelRequest, TravelResponse } from "@/lib/types";
import { TravelResponseSchema } from "@/lib/validation";

type OpenAIUsage = {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
} | null;

type CompletionResult = {
  plan: TravelResponse;
  usage: OpenAIUsage;
  attempts: number;
};

type GenerateOptions = {
  model: string;
  retries: number;
  timeoutMs: number;
};

type ParseCompletionClient = Pick<OpenAI, "beta">;

export async function generateTravelPlanWithLLM(
  client: ParseCompletionClient,
  input: TravelRequest,
  options: GenerateOptions,
): Promise<CompletionResult> {
  let attempts = 0;
  const completion = await withTimeout(
    withRetry(
      async () => {
        attempts += 1;
        return client.beta.chat.completions.parse({
          model: options.model,
          temperature: 0.4,
          messages: [
            { role: "system", content: TRAVEL_SYSTEM_PROMPT },
            { role: "user", content: buildTravelUserPrompt(input) },
          ],
          response_format: zodResponseFormat(TravelResponseSchema, "travel_plan"),
        });
      },
      {
        retries: options.retries,
        baseDelayMs: 300,
        maxDelayMs: 2000,
        shouldRetry: isRetryableOpenAIError,
      },
    ),
    options.timeoutMs,
    `Model request exceeded ${options.timeoutMs}ms timeout.`,
  );

  const parsed = completion.choices[0]?.message?.parsed;
  const rawContent = completion.choices[0]?.message?.content;

  if (!parsed && !rawContent) {
    throw new Error("No itinerary generated by model.");
  }

  const response = parsed ?? TravelResponseSchema.parse(JSON.parse(rawContent ?? "{}"));
  validateDailyPlanAgainstDates(input, response);

  return {
    plan: response,
    usage: completion.usage ?? null,
    attempts,
  };
}

export function validateDailyPlanAgainstDates(input: TravelRequest, plan: TravelResponse): void {
  const expectedDays = getDateSpanDays(input.startDate, input.endDate);
  if (plan.daily_plan.length !== expectedDays) {
    throw new Error(
      `Daily plan day count mismatch. Expected ${expectedDays}, received ${plan.daily_plan.length}.`,
    );
  }

  const expectedDates = buildDateRange(input.startDate, input.endDate);
  for (let index = 0; index < expectedDates.length; index += 1) {
    const day = plan.daily_plan[index];
    const expectedDayNumber = index + 1;
    if (day.day !== expectedDayNumber) {
      throw new Error(`Daily plan day index mismatch at position ${expectedDayNumber}.`);
    }
    if (day.date !== expectedDates[index]) {
      throw new Error(
        `Daily plan date mismatch at day ${expectedDayNumber}. Expected ${expectedDates[index]}, received ${day.date}.`,
      );
    }
  }
}

function isRetryableOpenAIError(error: unknown): boolean {
  const maybeError = error as { status?: number; code?: string; message?: string };
  const status = maybeError.status;
  if (typeof status === "number" && (status === 408 || status === 409 || status === 429 || status >= 500)) {
    return true;
  }

  if (maybeError.code && ["ETIMEDOUT", "ECONNRESET", "ECONNREFUSED"].includes(maybeError.code)) {
    return true;
  }

  if (typeof maybeError.message === "string") {
    const message = maybeError.message.toLowerCase();
    return message.includes("rate limit") || message.includes("temporarily unavailable");
  }

  return false;
}
